# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 576)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBoxPlaylist = QtWidgets.QGroupBox(Dialog)
        self.groupBoxPlaylist.setObjectName("groupBoxPlaylist")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBoxPlaylist)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayoutPlaylist = QtWidgets.QHBoxLayout()
        self.horizontalLayoutPlaylist.setObjectName("horizontalLayoutPlaylist")
        self.verticalLayout0 = QtWidgets.QVBoxLayout()
        self.verticalLayout0.setObjectName("verticalLayout0")
        self.label = QtWidgets.QLabel(self.groupBoxPlaylist)
        self.label.setObjectName("label")
        self.verticalLayout0.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.groupBoxPlaylist)
        self.label_2.setObjectName("label_2")
        self.verticalLayout0.addWidget(self.label_2)
        self.horizontalLayoutPlaylist.addLayout(self.verticalLayout0)
        self.verticalLayout1 = QtWidgets.QVBoxLayout()
        self.verticalLayout1.setObjectName("verticalLayout1")
        self.playlistHost = QtWidgets.QLineEdit(self.groupBoxPlaylist)
        self.playlistHost.setObjectName("playlistHost")
        self.verticalLayout1.addWidget(self.playlistHost)
        self.playlistURL = QtWidgets.QLineEdit(self.groupBoxPlaylist)
        self.playlistURL.setObjectName("playlistURL")
        self.verticalLayout1.addWidget(self.playlistURL)
        self.horizontalLayoutPlaylist.addLayout(self.verticalLayout1)
        self.verticalLayout_2.addLayout(self.horizontalLayoutPlaylist)
        self.verticalLayout.addWidget(self.groupBoxPlaylist)
        self.groupBoxPlayer = QtWidgets.QGroupBox(Dialog)
        self.groupBoxPlayer.setObjectName("groupBoxPlayer")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBoxPlayer)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayoutPlayer = QtWidgets.QHBoxLayout()
        self.horizontalLayoutPlayer.setObjectName("horizontalLayoutPlayer")
        self.verticalLayout2 = QtWidgets.QVBoxLayout()
        self.verticalLayout2.setObjectName("verticalLayout2")
        self.label_3 = QtWidgets.QLabel(self.groupBoxPlayer)
        self.label_3.setObjectName("label_3")
        self.verticalLayout2.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.groupBoxPlayer)
        self.label_4.setObjectName("label_4")
        self.verticalLayout2.addWidget(self.label_4)
        self.horizontalLayoutPlayer.addLayout(self.verticalLayout2)
        self.verticalLayout3 = QtWidgets.QVBoxLayout()
        self.verticalLayout3.setObjectName("verticalLayout3")
        self.playerPath = QtWidgets.QLineEdit(self.groupBoxPlayer)
        self.playerPath.setObjectName("playerPath")
        self.verticalLayout3.addWidget(self.playerPath)
        self.playerOptions = QtWidgets.QLineEdit(self.groupBoxPlayer)
        self.playerOptions.setObjectName("playerOptions")
        self.verticalLayout3.addWidget(self.playerOptions)
        self.horizontalLayoutPlayer.addLayout(self.verticalLayout3)
        self.verticalLayout_3.addLayout(self.horizontalLayoutPlayer)
        self.verticalLayout.addWidget(self.groupBoxPlayer)
        self.groupBoxGuide = QtWidgets.QGroupBox(Dialog)
        self.groupBoxGuide.setObjectName("groupBoxGuide")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBoxGuide)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayoutGuide = QtWidgets.QHBoxLayout()
        self.horizontalLayoutGuide.setObjectName("horizontalLayoutGuide")
        self.verticalLayout4 = QtWidgets.QVBoxLayout()
        self.verticalLayout4.setObjectName("verticalLayout4")
        self.label_5 = QtWidgets.QLabel(self.groupBoxGuide)
        self.label_5.setObjectName("label_5")
        self.verticalLayout4.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.groupBoxGuide)
        self.label_6.setObjectName("label_6")
        self.verticalLayout4.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.groupBoxGuide)
        self.label_7.setObjectName("label_7")
        self.verticalLayout4.addWidget(self.label_7)
        self.horizontalLayoutGuide.addLayout(self.verticalLayout4)
        self.verticalLayout5 = QtWidgets.QVBoxLayout()
        self.verticalLayout5.setObjectName("verticalLayout5")
        self.epgHost = QtWidgets.QLineEdit(self.groupBoxGuide)
        self.epgHost.setObjectName("epgHost")
        self.verticalLayout5.addWidget(self.epgHost)
        self.epgIndex = QtWidgets.QLineEdit(self.groupBoxGuide)
        self.epgIndex.setObjectName("epgIndex")
        self.verticalLayout5.addWidget(self.epgIndex)
        self.epgURL = QtWidgets.QLineEdit(self.groupBoxGuide)
        self.epgURL.setObjectName("epgURL")
        self.verticalLayout5.addWidget(self.epgURL)
        self.horizontalLayoutGuide.addLayout(self.verticalLayout5)
        self.verticalLayout_4.addLayout(self.horizontalLayoutGuide)
        self.horizontalLayoutAl = QtWidgets.QHBoxLayout()
        self.horizontalLayoutAl.setObjectName("horizontalLayoutAl")
        self.label_8 = QtWidgets.QLabel(self.groupBoxGuide)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.horizontalLayoutAl.addWidget(self.label_8)
        self.aliasAddButton = QtWidgets.QPushButton(self.groupBoxGuide)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.aliasAddButton.sizePolicy().hasHeightForWidth())
        self.aliasAddButton.setSizePolicy(sizePolicy)
        self.aliasAddButton.setObjectName("aliasAddButton")
        self.horizontalLayoutAl.addWidget(self.aliasAddButton)
        self.aliasDelButton = QtWidgets.QPushButton(self.groupBoxGuide)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.aliasDelButton.sizePolicy().hasHeightForWidth())
        self.aliasDelButton.setSizePolicy(sizePolicy)
        self.aliasDelButton.setObjectName("aliasDelButton")
        self.horizontalLayoutAl.addWidget(self.aliasDelButton)
        self.verticalLayout_4.addLayout(self.horizontalLayoutAl)
        self.tableAliases = QtWidgets.QTableWidget(self.groupBoxGuide)
        self.tableAliases.setEditTriggers(QtWidgets.QAbstractItemView.AllEditTriggers)
        self.tableAliases.setTabKeyNavigation(True)
        self.tableAliases.setProperty("showDropIndicator", False)
        self.tableAliases.setAlternatingRowColors(True)
        self.tableAliases.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableAliases.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableAliases.setColumnCount(2)
        self.tableAliases.setObjectName("tableAliases")
        self.tableAliases.setRowCount(0)
        self.tableAliases.horizontalHeader().setVisible(True)
        self.tableAliases.horizontalHeader().setCascadingSectionResizes(True)
        self.tableAliases.horizontalHeader().setDefaultSectionSize(165)
        self.tableAliases.verticalHeader().setVisible(False)
        self.verticalLayout_4.addWidget(self.tableAliases)
        self.verticalLayout.addWidget(self.groupBoxGuide)
        self.errorLabel = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.errorLabel.sizePolicy().hasHeightForWidth())
        self.errorLabel.setSizePolicy(sizePolicy)
        self.errorLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.errorLabel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.errorLabel.setText("")
        self.errorLabel.setWordWrap(True)
        self.errorLabel.setObjectName("errorLabel")
        self.verticalLayout.addWidget(self.errorLabel)
        self.horizontalLayoutBt = QtWidgets.QHBoxLayout()
        self.horizontalLayoutBt.setObjectName("horizontalLayoutBt")
        self.defaultsButton = QtWidgets.QPushButton(Dialog)
        self.defaultsButton.setObjectName("defaultsButton")
        self.horizontalLayoutBt.addWidget(self.defaultsButton)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayoutBt.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayoutBt)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "tvnao - settings"))
        self.groupBoxPlaylist.setTitle(_translate("Dialog", "Playlist"))
        self.label.setText(_translate("Dialog", "Host:"))
        self.label_2.setText(_translate("Dialog", "URL:"))
        self.groupBoxPlayer.setTitle(_translate("Dialog", "Player"))
        self.label_3.setText(_translate("Dialog", "Path:"))
        self.label_4.setText(_translate("Dialog", "Options:"))
        self.groupBoxGuide.setTitle(_translate("Dialog", "Program Guide"))
        self.label_5.setText(_translate("Dialog", "Host:"))
        self.label_6.setText(_translate("Dialog", "Index:"))
        self.label_7.setText(_translate("Dialog", "URL:"))
        self.label_8.setText(_translate("Dialog", "Replacements:"))
        self.aliasAddButton.setToolTip(_translate("Dialog", "Connect channel name in playlist to a name in TV guide"))
        self.aliasAddButton.setText(_translate("Dialog", "Add"))
        self.aliasDelButton.setText(_translate("Dialog", "Del"))
        self.tableAliases.setToolTip(_translate("Dialog", "channel name from playlist / channel name from TV guide"))
        self.tableAliases.setSortingEnabled(True)
        self.defaultsButton.setText(_translate("Dialog", "Defaults"))

