# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'timeshift_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TimeshiftDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(439, 377)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.hostLabel = QtWidgets.QLabel(Dialog)
        self.hostLabel.setObjectName("hostLabel")
        self.gridLayout_2.addWidget(self.hostLabel, 0, 0, 1, 1)
        self.portLabel = QtWidgets.QLabel(Dialog)
        self.portLabel.setObjectName("portLabel")
        self.gridLayout_2.addWidget(self.portLabel, 0, 1, 1, 2)
        self.hostEdit = QtWidgets.QLineEdit(Dialog)
        self.hostEdit.setObjectName("hostEdit")
        self.gridLayout_2.addWidget(self.hostEdit, 1, 0, 1, 1)
        self.listWidget = QtWidgets.QListWidget(Dialog)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout_2.addWidget(self.listWidget, 3, 0, 1, 3)
        self.audioLabel = QtWidgets.QLabel(Dialog)
        self.audioLabel.setObjectName("audioLabel")
        self.gridLayout_2.addWidget(self.audioLabel, 2, 0, 1, 1)
        self.portEdit = QtWidgets.QLineEdit(Dialog)
        self.portEdit.setObjectName("portEdit")
        self.gridLayout_2.addWidget(self.portEdit, 1, 1, 1, 2)
        self.audioSpinBox = QtWidgets.QSpinBox(Dialog)
        self.audioSpinBox.setMinimum(1)
        self.audioSpinBox.setProperty("value", 1)
        self.audioSpinBox.setObjectName("audioSpinBox")
        self.gridLayout_2.addWidget(self.audioSpinBox, 2, 1, 1, 2)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 4, 1, 1, 2)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.hostLabel.setText(_translate("Dialog", "Host:"))
        self.portLabel.setText(_translate("Dialog", "Port:"))
        self.audioLabel.setText(_translate("Dialog", "Audio Channel:"))
